---
title: "About me"
format:
  html:
    theme: lumen
---

I am a sociologist and demographer based at IRIS (Inserm, Université Sorbonne Paris Nord), where I hold a Junior Professor Chair on "health inequalities". My work focuses on health inequalities in relation to gender and (paid and unpaid) work. I am particularly interested in studying how the accumulation of different experiences in the employment and family spheres shapes differences in health between men and women, and among them. I mainly use quantitative methods, which I combine with biographical interviews in mixed-methods designs. I adopt a life course perspective and consider multiple health dimensions (mental health, disability, chronic diseases and biomarkers).

## Employment and education

**Junior Professor**, IRIS (Inserm, Université Sorbonne Paris Nord, CNRS, EHESS) \
*Feb. 2026 – Today*

**Postdoctoral Researcher**, IRIS (Inserm, Université Sorbonne Paris Nord, CNRS, EHESS) – *ANR ACCESS ERC postdoctoral fellowship*\
*Oct. 2025 – Feb. 2026*

**Postdoctoral Researcher**, King’s College London – *Centre for Society and Mental Health, Global Institute of Women's Leadership*\
*June 2023 – Oct. 2025*

**Postdoctoral Researcher**, French National Institute for Demographic Studies (Ined) – *ANR GINCO*\
*Dec. 2022 – June 2023*

**Ph.D. in Sociology–Demography**, University Paris-Saclay / Ined\
*Sept. 2018 – Nov. 2022*

**Master’s in Quantitative Sociology and Demography (M1 & M2)**, University Paris-Saclay\
*Sept. 2017 – Aug. 2018*
